sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - gcc
    - freeglut3-dev
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-ttf2.0-dev
    - libsdl-gfx1.2-dev
    - libsdl-net1.2-dev
    - libboost-dev
    - libboost-all-dev
    - libopenal-dev
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
#- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - make
#  - make test


  #download libSGE
  #- git clone https://github.com/flibitijibibo/libSGE
  #- git checkout 3facdc9
  #- cd libSGE && sudo make install
